# NOTE: do not gofmt -w here. Upstream carries ~31 files with pre-existing
# gofmt deviations (old-style doc-comment indentation). Reformatting them would
# produce a large diff against upstream and conflict on every rebase — the exact
# cost this split exists to avoid. The rename itself introduces no new ones.#!/usr/bin/env bash
# Rewrite the module path from upstream's to this fork's.
#
# Go resolves an import by its path, so a fork that keeps `module
# github.com/go-git/go-git/v5` cannot be imported as itself: every internal
# import would resolve to real upstream and the build would link two copies of
# the library. Renaming is therefore not optional — but it touches ~340 files and
# would conflict with every upstream change if it lived in the patch series.
#
# So it does not live there. The `metallic-base` branch holds ONLY the additive
# patches with upstream's import paths untouched, which is what makes
# `git rebase upstream/<tag>` near-conflict-free. This script regenerates the
# importable `metallic` branch from it mechanically:
#
#   git checkout metallic-base
#   git rebase v5.20.0            # or whatever the new upstream tag is
#   ./scripts/metallic-rename.sh --commit
#
# Re-running is safe; the rewrite is idempotent.
set -euo pipefail

UPSTREAM="github.com/go-git/go-git/v5"
FORK="github.com/lunarhue/metallic-flock-go-git/v5"

cd "$(dirname "$0")/.."

files=$(grep -rl --include='*.go' --include='go.mod' -F "$UPSTREAM" . || true)
if [ -z "$files" ]; then
  echo "nothing to rewrite (already renamed?)"
else
  echo "$files" | xargs sed -i "s|$UPSTREAM|$FORK|g"
  echo "rewrote $(echo "$files" | wc -l) files"
fi

gofmt -l . | grep -v '^_examples/' || true

if [ "${1:-}" = "--commit" ]; then
  git add -A
  git commit -q -m "rename module path to $FORK (generated by scripts/metallic-rename.sh)"
  echo "committed"
fi
